services:
  gha:
    build:
      context: .
    # if you don't want to build and instead just use the pre-built image
    # comment out the build block above and uncomment below
    # image: compscidr/github-runner-android
    container_name: gha
    env_file:
      - .env
    restart: always
    # uncomment below for interactive debugging, this will override the normal entrypoint and prevent
    # gh actions runner from starting up, but is good for debugging path issues, etc.
#    entrypoint: /bin/bash
#    tty: true
#    stdin_open: true
